import { Geist, Geist_Mono, Gabarito } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata = {
  title: "Moolen Trip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} antialiased bg-color-dark`}
        suppressHydrationWarning={true}
      >
        <Navbar />
        <main className="pt-24">{children}</main>
      </body>
    </html>
  );
}
