import { Geist, Geist_Mono, Gabarito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "../components/Footer";
import { AuthContextProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata = {
  title: "Moolen Trip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} antialiased bg-color-dark`}
        suppressHydrationWarning={true}
      >
        <AuthContextProvider>
          <Navbar />
          <main className="pt-36 lg:pt-24 bg-[#f4f3ec] py-8">{children}</main>
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
